name: Content typos tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check spelling of markdown and JSON files in content directory
        uses: crate-ci/typos@master
        with:
          files: ./content/**/*.{md,json}
